import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {createTheme, ThemeProvider} from "@mui/material";
import connectDBIfNotConnected from "@/database";
import React from "react";

await connectDBIfNotConnected()
const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout(props: {
    dialog: React.ReactNode,
    children: React.ReactNode;
})
{


    return (
        <html lang="en" dir={"rtl"}>
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <div>{props.dialog}</div>
        <div>{props.children}</div>
        </body>
        </html>
    );
}
